config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  default_scope { order(created_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = 'Article has been created'
      redirect_to articles_path
    else
      flash.now[:danger] = 'Article has not been created'
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path, class: "btn btn-secondary btn-lg", id: "new-article-btn" %>

<br /> <br />

<% @articles.each do |article| %>
  <div class="card mb-4">
    <div class="card-header">
      <h1><%= link_to article.title, article_path(article) %></h3>
    </div>
    <div class="card-body">
      <p><%= truncate(article.body, length: 500) %></p>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding New Article</h3>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, html: {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @article.errors.any? %>
        <div class="card text-white bg-danger offset-md-1">
          <div class="card-header">
            <h2 class="card-title">
              <%= pluralize(@article.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
            <div class="card-block">
              <ul>
                <% @article.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      <br />
      <div class="form-group row">
        <div class="control-label col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-11">
          <%= f.text_field :title, class:'form-control', placeholder:"Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="control-label col-md-1">
          <%= f.label :body %>
        </div>
        <div class="col-md-11">
          <%= f.text_area :body, rows: 10, class:'form-control', placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-12">
          <%= f.submit class:"btn btn-primary btn-lg float-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Longerich</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <%= link_to "Longeri.ch", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Michael", "#", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Deborah", "#", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Aliyah", "#", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Eli", "#", class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <br />
          <% flash.each do |key, message| %>
            <div class="text-center alert alert-<%= key == 'notice' ? 'success' : "danger" %>">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>